### ISSUE TITLE
Do we need to plug in power in our Apple TV AND micro-USB? It doesn't detect my apple tv A1469 :( (xcode 12.4, macos 10.15.7)

### ISSUE THREAD

**Issue by activea** [NSSpiral/Blackb0x#10]

**Comment by NSSpiral** [comment]
Yes, plug in the power cable and a micro-USB.

**Comment by activea** [comment]
> Yes, plug in the power cable and a micro-USB.

Thanks a lot. Although i connect both cables, the program doesn't detect the device. I have tried two micro-USB cables. Since iTunes is missing i can't detect if Apple TV is connected to my macbook :(

**Comment by NSSpiral** [comment]
You can see it listed on the left side of Finder under the Locations group if you're on a version of macOS without iTunes.

**Comment by goldenx1** [comment]
‘Waiting for Apple TV to reboot’ Apple TV 2g
I’ve connected the usb and power cable run the jailbreak and it gets stuck on ‘waiting for Apple TV to reboot’ connected the hdmi and Apple TV is on but I don’t see anything new even after a waiting a while. I’m I doing something wrong?

**Comment by activea** [comment]
> ut I don’t see anything new even after a waiting a while. I’m I doing something wrong?

I have the same problem too!!

**Comment by activea** [comment]
> ‘Waiting for Apple TV to reboot’ Apple TV 2g
> I’ve connected the usb and power cable run the jailbreak and it gets stuck on ‘waiting for Apple TV to reboot’ connected the hdmi and Apple TV is on but I don’t see anything new even after a waiting a while. I’m I doing something wrong?

I have the same problem too!

**Comment by activea** [comment]
> Locations

**Comment by activea** [comment]
> You can see it listed on the left side of Finder under the Locations group if you're on a version of macOS without iTunes.

I can't find it!!

**Comment by NSSpiral** [comment]
> ‘Waiting for Apple TV to reboot’ Apple TV 2g
> I’ve connected the usb and power cable run the jailbreak and it gets stuck on ‘waiting for Apple TV to reboot’ connected the hdmi and Apple TV is on but I don’t see anything new even after a waiting a while. I’m I doing something wrong?

You have to tether boot now using Blackb0x (assuming you're on the latest firmware). Then the installer will load Kodi in the background. If you prefer an untethered jailbreak, install 5.3 firmware and jailbreak again.

**Comment by goldenx1** [comment]
> > ‘Waiting for Apple TV to reboot’ Apple TV 2g
> > I’ve connected the usb and power cable run the jailbreak and it gets stuck on ‘waiting for Apple TV to reboot’ connected the hdmi and Apple TV is on but I don’t see anything new even after a waiting a while. I’m I doing something wrong?
> 
> You have to tether boot now using Blackb0x (assuming you're on the latest firmware). Then the installer will load Kodi in the background. If you prefer an untethered jailbreak, install 5.3 firmware and jailbreak again.

After clicking the tether boot it is stuck on ‘waiting for Apple TV to boot’ is there anything else I need to do?

**Comment by NSSpiral** [comment]
Did you plug in the power and micro-USB to tether boot?

**Comment by activea** [comment]
> tether boot

 How to tether boot ????

**Comment by NSSpiral** [comment]
> > tether boot
> 
> How to tether boot ????

Open blackb0x, plug Apple TV in (DFU or Normal - doesn't matter), click Tethered Boot instead of Jailbreak this time.

**Comment by activea** [comment]
![image](https://user-images.githubusercontent.com/534503/125059761-5a616700-e0b4-11eb-847f-39d0dc135864.png)
I'm stuck here :(

**Comment by NSSpiral** [comment]
Does your Apple TV come up on the left panel of Finder? If not you have other problems with your computer detecting it. Would need to fix those before blackb0x can see it. Try a different USB port or micro-USB cable.

**Comment by activea** [comment]
> Does your Apple TV come up on the left panel of Finder? If not you have other problems with your computer detecting it. Would need to fix those before blackb0x can see it. Try a different USB port or micro-USB cable.

No, the Apple TV doesn't come up on the left panel of Finder.. I have tried several cables...no luck :(

**Comment by NSSpiral** [comment]
Your problem seems to be unrelated to blackb0x. Once you're able to get the Apple TV to show up in Finder then blackb0x should recognise it.

**Comment by sudonto** [comment]
@activea I face this problem, too. you may check your cable with other device (samsung or else?) and see if your Windows computer can detect it or not. Info then the cable does not have data

**Comment by activea** [comment]
> @activea I face this problem, too. you may check your cable with other device (samsung or else?) and see if your Windows computer can detect it or not. If not then the cable does not have data pin

Finally i solved the problem by finding a cable that can transfer data and not only charge !! After that the Blackb0x works fine!!
