### ISSUE TITLE
Waiting for Apple TV to reboot

### ISSUE THREAD

**Issue by goldenx1** [NSSpiral/Blackb0x#11]
Waiting for Apple TV to reboot’ Apple TV 2g
I’ve connected the usb and power cable run the jailbreak and it gets stuck on ‘waiting for Apple TV to reboot’ connected the hdmi and Apple TV is on but I don’t see anything new even after a waiting a while. I’m I doing something wrong?

**Comment by greenairsystems** [comment]
Same here. Following

**Comment by NSSpiral** [comment]
You have to tether boot now using Blackb0x (assuming you're on the latest firmware). Then the installer will load Kodi in the background. If you prefer an untethered jailbreak, install 5.3 firmware and jailbreak again.

**Comment by NSSpiral** [comment]
> Same here on Apple TV A1469, 7.7 (8153)
> Only hard reset (plugging the power cable) makes it reboot into original condition (no jailbreak).

Did you get a message box saying the Jailbreak completed and to connect your Apple TV to the TV before unplugging?

**Comment by greenairsystems** [comment]
> Did you get a message box saying the Jailbreak completed and to connect your Apple TV to the TV before unplugging?
no, but I not only got a coffee, but went grocery shopping (30 minutes). So the jailbreak probably got stuck?
Or how long can it possibly take?

**Comment by greenairsystems** [comment]
Third time's a charm. It did work on the third attempt. I had to put the box into restore mood first, otherwise Balckb0x would crash at start. Waiting for the reboot now.
