### ISSUE TITLE
Does he need Arduino Uno for Apple TV 3,1 (A1427)

### ISSUE THREAD

**Issue by mobde** [NSSpiral/Blackb0x#12]
Does he need order to perform this on Apple TV 3,1 (A1427) you need Arduino Uno ?

**Comment by NSSpiral** [comment]
Apple TV 3,1 (A1427) requires an Arduino with a USB Host Shield and checkm8-A5 to PWN it first.

**Comment by NSSpiral** [comment]
https://github.com/synackuk/checkm8-a5
Arduino needs to be genuine, make sure not to buy a clone (they can have problems with the USB Host Shield).
