### ISSUE TITLE
Jailbreak installed but Kodi not

### ISSUE THREAD

**Issue by section83** [NSSpiral/Blackb0x#126]
I can't get Blackb0x to install Kodi.  I followed the steps until Boackb0x reported "Jailbreak installed".  I then waited for 30 minutes but nothing seemed to happen.  I did quit from iTunes which automatically started when I put the ATV into DFU mode.  But, that didn't seem to achieve anything.

Blackb0x is showing this:

![Blackb0x](https://user-images.githubusercontent.com/7471595/180632475-30ac2ca7-bae3-4bb1-8288-74edf5cb60f8.png)

The Apple TV is showing this:

![ATV](https://user-images.githubusercontent.com/7471595/180632479-c5db9716-2a57-449f-895e-dc1cca491107.jpg)

Is there anything to do to get Kodi installed ?

**Comment by vlumikero** [comment]
I'm not getting Kodi either. I'm trying to install it manually, but the apt-get command fails with a 
```
failed to write (No space left on device)
```

and it appears that the primary partition is almost full:
```
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/disk0s1s1   1364616 1246488    104484  93% /
devfs                 27      27         0 100% /dev
/dev/disk0s1s2   6376824  251076   6125748   4% /private/var
```

@NSSpiral any ideas on how to get around this?

**Comment by section83** [comment]
I ran the procedure a few times with the same result, then, I noticed that Kodi had been installed !  So, I guess it does work but, I don't know when or how Kodi was installed. Along the way there were confusing and contradictory windows open in Blackb0x.  Anyway, now I wonder how to make Kodi add-ons work – so far none of the 15 or so I've tried work.
