### ISSUE TITLE
No sign of jailbreak

### ISSUE THREAD

**Issue by JxxIT** [NSSpiral/Blackb0x#138]
I plugged in the usb and hdmi at once on my appletv 3.

Now Blackb0x is stuck at Jailbreak is active on device.
Can anyone please help?

**Comment by jormor1991** [comment]
I'm having the same issue. Says Jailbreak is active on device but it's still stuck in recovery mode.

**Comment by JxxIT** [comment]
Wow im dumb, i have a appletv 3.1 and no arduino. This solves my problem. @jormor1991 please open a new issue.
