### ISSUE TITLE
Jailbreak apple tv 3 gen 

### ISSUE THREAD

**Issue by BertL1005** [NSSpiral/Blackb0x#14]
I habe downloaded on a mac with high sierra the blackbox app, connected my apple tv via usb klick on the apple tv and do the combination to enter dfu mode i think and then klick install jailbreak. when is the jailbreak done ? my apple tv blinks fast and on the mac there is nothing noted like install jailbreak or something. I can already click again to the apple tv and install jailbreak but nothing appears. what did i wrong ?

**Comment by adaschum** [comment]
Connect it to your tv and see if the Kodi app appears after 10 minutes.  Mine came later after I thought the Jailbreak failed.

**Comment by BertL1005** [comment]
How did you take the jailbreak on your Apple TV ?

**Comment by BertL1005** [comment]
I can after jailbreak only cut off the power and power on. Is this normal ? 
Kodi is not on my screen. I'm now on the home screen of my Apple TV and wait a little time.

**Comment by rmaestrali** [comment]
Same happened with me, ATV 3, run the Blackbox, Jailbreak, wait for 15m and connected to the TV,,, Kodi did not appear

**Comment by joshblah555** [comment]
> Same happened with me, ATV 3, run the Blackbox, Jailbreak, wait for 15m and connected to the TV,,, Kodi did not appear

Did you unplug the power?

**Comment by BertL1005** [comment]
I have unplugged the power, because there is no other way to start the apple tv. It is always in the recovery or dfu mode, the led blinks

**Comment by bigboigahoy** [comment]
> I have unplugged the power, because there is no other way to start the apple tv. It is always in the recovery or dfu mode, the led blinks

I also have to unplug once jailbreak is finished to get it to actual start the system. Kodi does not show up for me either. Perhaps we need to wait longer in the DFU screen and it will eventually reboot?

**Comment by NSSpiral** [comment]
> Same happened with me, ATV 3, run the Blackbox, Jailbreak, wait for 15m and connected to the TV,,, Kodi did not appear

Try jailbreak with v0.4 and then wait a short time after connecting the Apple TV to the TV for Kodi/nitoTV to appear. Make sure your Apple TV is connected to your network when it boots.

**Comment by BertL1005** [comment]
> > Same happened with me, ATV 3, run the Blackbox, Jailbreak, wait for 15m and connected to the TV,,, Kodi did not appear
> 
> Try jailbreak with v0.4 and then wait a short time after connecting the Apple TV to the TV for Kodi/nitoTV to appear. Make sure your Apple TV is connected to your network when it boots.

When i connect the atv to the tv it is always in dfu mode and it doesnt reboot . Then i disconnect the power and connect the power on and the atv starts normaly without kodi. Connect to the internet via lan cable ?

**Comment by syproduction** [comment]
I just didnt get it what i should see when successful jailbreak?
You said: connect to tv and wait 10 minutes. Should ATV boot to its normal menu, and then somewhere we'll find Kodi? Or it will completely switch to Kodi fullscreen itself? Or should it look different after successful jailbreak?
Because mine looks the same (A1427), did Checkm8, did jailbreak, didn't do Tethered Boot

**Comment by NSSpiral** [comment]
> I just didnt get it what i should see when successful jailbreak?
> You said: connect to tv and wait 10 minutes. Should ATV boot to its normal menu, and then somewhere we'll find Kodi? Or it will completely switch to Kodi fullscreen itself? Or should it look different after successful jailbreak?
> Because mine looks the same (A1427), did Checkm8, did jailbreak, didn't do Tethered Boot

After doing the jailbreak a message will pop up after the Apple TV has automatically rebooted telling you to plug it into the TV. Once it starts (assuming it has an internet connection) it will automatically load Kodi onto the home screen and refresh.
