### ISSUE TITLE
I am not able to jailbreak my A1469

### ISSUE THREAD

**Issue by wendells01** [NSSpiral/Blackb0x#147]
I need help, I'm trying to install Blackb0x Jailbreak on Apple TV 3rd generation A1469 but I'm not succeeding, after Jailbreak completes the process, nothing happens, Apple TV does not restart and if I force restart (holding the menu button and play/pause button) Kodi does not appear

**Comment by JxxIT** [comment]
How did you fix this, I have the same issue?
