### ISSUE TITLE
Unable to be opened at a M1 Macbook Pro 

### ISSUE THREAD

**Issue by hpware** [NSSpiral/Blackb0x#160]
I tried opening old versions of the software in the release tab. However, it still won't work.
Try fixing this in 0.6.3 :)
<img width="413" alt="Screenshot 2024-04-27 at 22 03 19" src="https://github.com/NSSpiral/Blackb0x/assets/157942818/586fd55b-4583-4942-9e26-b5cd89e02414">

**Comment by LionCave97** [comment]
You need to right click to open. It works on mine perfectly.

**Comment by hpware** [comment]
> You need to right click to open. It works on mine perfectly.

I retried still didn't work :( 
<img width="413" alt="Screenshot 2024-05-03 at 00 15 45" src="https://github.com/NSSpiral/Blackb0x/assets/157942818/ff1ffbde-1556-4a74-9395-afa48c1d34fd">

**Comment by SpamixOfficial** [comment]
> > You need to right click to open. It works on mine perfectly.
> 
> I retried still didn't work :( <img alt="Screenshot 2024-05-03 at 00 15 45" width="413" src="https://private-user-images.githubusercontent.com/157942818/327503230-ff1ffbde-1556-4a74-9395-afa48c1d34fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDA4NzIsIm5iZiI6MTcxOTUwMDU3MiwicGF0aCI6Ii8xNTc5NDI4MTgvMzI3NTAzMjMwLWZmMWZmYmRlLTE1NTYtNGE3NC05Mzk1LWFmYTQ4YzFkMzRmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNTAyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjQ3YTdmMDNjMmEyMTQ3OWUwZWQ4NTViYmE5YzBjNGRkMjBiZGIzODVmNzEzNzc1M2NkZGFiMWYzNjQ2NjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5lycfol9ugMz2ujSnSXveg9cvlD0EHaTiYb2UawBidA">

try redownloading the application. Most likely you got a bad download (has happened to me a couple of times with other apps). If the problem still arises then it is most likely an issue with your MacOS.

**Comment by hpware** [comment]
Ok.
