### ISSUE TITLE
ATV3,1 fail to jailbreak

### ISSUE THREAD

**Issue by 0nenZer0** [NSSpiral/Blackb0x#17]
Hi, Trying this in ATV3,1 but seems failing to upload iBEC then waiting for ATV to reboot. Tried to use Ardunio Uno and Mini. Successfully Pawned but wasn't able to complete the jailbreak. Any help?

To device AppleTV3,1
Packed Img3 image
Detect iBSS/LLB imagenUploading soft DFU
progress 2.777778 ....
.....
progress 100.000000
Sent
Sending iBEC -> Connected to Apple TV
Unable to upload data to device
Sent
Sending DeviceTree -> Connected to Apple TV
Sent
Sending Ramdisk -> Connected to Apple TV
Sent
Sending KernelCache -> Connected to Apple TV
Sent

**Comment by NSSpiral** [comment]
Did you make sure to use synackuk's fork of checkm8-a5 and not a1exdandy's?

**Comment by NSSpiral** [comment]
Also try multiple times, I found it doesn't always work correctly (even though it appears to).

**Comment by 0nenZer0** [comment]
@NSSpiral My bad. after checking found I flashed the one from a1exdandy's fork. Will re-flash with correct fork and give it a try. Thanks for ur help

**Comment by 0nenZer0** [comment]
Got nito and Kodi in my ATV3,1 ... thanks @NSSpiral
