### ISSUE TITLE
No Kodi, no NitoTV

### ISSUE THREAD

**Issue by monte71** [NSSpiral/Blackb0x#2]
After sucessful jailbreak and reboot I was waiting a while to see Kodi and NitoTV to be installed but none of that happened. After about 10 minutes Springboard reloaded but still no sight of 3rd party tools. Any idea how I can check what went wrong?

AppleTV 3,2 8.4.4

**Comment by NSSpiral** [comment]
Use iFunbox or iMazing and double click the blackb0x.log file in /var/mobile/Media. Paste what's in there so I can see where it failed.

After pasting that try restarting the Apple TV and see if Kodi appears.

**Comment by monte71** [comment]
Starting post-install
Updating apt
Update failed
Installing debs
Installing substrate
Upgrade failed
Installing nitoTV
Installing Kodi
Install AFC2
Finished installation

**Comment by NSSpiral** [comment]
Looking into it now

**Comment by NSSpiral** [comment]
Can you try using version 0.1 for now? I think there are issues with the nitoTV debs.

**Comment by monte71** [comment]
I tried 0.1 a few times but it always gets stuck at "Downloading Firmware components"

**Comment by pedroblourenco** [comment]
> I tried 0.1 a few times but it always gets stuck at "Downloading Firmware components"

I think I might be having the exact same issue on version 0.2. Looking forward for any hints on how to solve this.

**Comment by NSSpiral** [comment]
Try delete the files in /Users/<Your username>/Documents/Blackb0x/ and let the app download them again.

**Comment by monte71** [comment]
Now both 0.1 and 0.2 crashing immediately after connecting the AppleTV via USB. Deleting /Users/Your username/Documents/Blackb0x/ didn't help either. Strange.

**Comment by NSSpiral** [comment]
Completely power down the Apple TV and try reconnecting it again. If that doesn't help then try run the app via terminal (cd Blackb0x.app/Contents/MacOS/ then ./blackb0x) and paste the output.

**Comment by monte71** [comment]
I tried 0.2 again and it works fully fine besides not installing Kodi.

0.1 is stuck after this:
Downloaded kernelcache.release.j33i on slot 3
KernelCache downloaded - /Users/name/Documents/Blackb0x/AppleTV3,2_8.4.3_12H923_Restore/kernelcache.release.j33i

When re-trying 0.1 it's stuck here:
DeviceTree downloaded - /Users/joerg/Documents/Blackb0x/AppleTV3,2_8.4.3_12H923_Restore/Firmware/all_flash/all_flash.j33iap.production/DeviceTree.j33iap.img3

**Comment by NSSpiral** [comment]
Delete everything in Documents/Blackb0x, power down Apple TV and try 0.1 from scratch. I'm going to fix a few things tomorrow hopefully.

**Comment by NSSpiral** [comment]
Uploaded a new build (0.3). Should install both Kodi and nitoTV.

**Comment by fredseventyfive** [comment]
hello, it seems that on AppleTV 4K & HD jailbreakak nitoTV is very long to put in place repot apt
- Bingner.com non-functional

**Comment by monte71** [comment]
I tried installing 0.3 per the GUI (deleted everything from the Doc folder). The Gui got stuck with the orange bars for each of the components. I tried with Terminal. That worked but Kodi nor nitoTV got installed. Tried it a second time. No luck. blackb0x.log shows this:
Starting post-install
Updating apt

**Comment by monte71** [comment]
After a few minutes I've got this:
Starting post-install
Updating apt
Update failed
Installing debs
Installing substrate
Upgrade failed
Installing nitoTV
Installing Kodi
Install AFC2
Finished installation

But neither Kodi nor nitoTV show up actually.

**Comment by monte71** [comment]
Finally I've got nitoTV and Kodi. Needed to restore my AppleTV and then installed 0.3 again. Thanks for this great tool and support!
