### ISSUE TITLE
Released 4 crashes on MacOS 10.13.6

### ISSUE THREAD

**Issue by renatovertemati** [NSSpiral/Blackb0x#20]
Crashed on the first try after downloaded the packages. After that, it keeps crashing just after I try to start the whole process.

**Comment by NSSpiral** [comment]
Looking into fixing this.

**Comment by mammamorta** [comment]
10.12.6 (16G2136) crashing too.

Crashed Thread:        2  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/*/Blackb0x.app/Contents/MacOS/Blackb0x
  Expected in: /usr/lib/libSystem.B.dylib

Error Code:      0x02000209
Trap Number:     133

**Comment by NSSpiral** [comment]
> 
> 
> 10.12.6 (16G2136) crashing too.
> 
> Crashed Thread: 2 Dispatch queue: com.apple.root.default-qos
> 
> Exception Type: EXC_CRASH (SIGABRT)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note: EXC_CORPSE_NOTIFY
> 
> Termination Reason: DYLD, [0x4] Symbol missing
> 
> Dyld Error Message:
> Symbol not found: ____chkstk_darwin
> Referenced from: /private/var/folders/*/Blackb0x.app/Contents/MacOS/Blackb0x
> Expected in: /usr/lib/libSystem.B.dylib
> 
> Error Code: 0x02000209
> Trap Number: 133

Thanks for the log. I'm working on a fix.

**Comment by Jack06WS** [comment]
Same issue here. I'm looking forward to the fix!

**Comment by NSSpiral** [comment]
New build you might want to test. Should work 10.11+ with random possible crashes.
