### ISSUE TITLE
Jailbreak Apple TV 3,2

### ISSUE THREAD

**Issue by jurgverhoeven** [NSSpiral/Blackb0x#21]
Hello,

I installed the jailbreak (on Apple TV 3.2) and have Kodi and NitoTV, but when I click in NitoTV it takes A very long time to lead. I also cannot search for a package, because I get: Unable to read /etc/apt/apt.conf.d.
Also on Kodi I cannot find any installable plugins using the standard repo.

**Comment by joshblah555** [comment]
Both Kodi and nitoTV are extremely outdated for this 8-year-old device. Kodi 14 cannot use the latest sources but /should/ work with installing a source called TVAddons.

As for that issue, a fix will be coming soon as nitoTV will be updated as well.

**Comment by evitor** [comment]
i have the same problems..
