### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by syproduction** [NSSpiral/Blackb0x#22]
Wtf why there is no compiled binary? Xcode is throwing error on Big Sur and on Mojave:

`No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "E4V2A7WYY7" with a private key was found.`

I spent a day installing xcode on a MacBook just to compile this and still the same error, i thought it was version problem.

**Comment by joshblah555** [comment]
> Wtf why there is no compiled binary? Xcode is throwing error on Big Sur and on Mojave:
> 
> `No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "E4V2A7WYY7" with a private key was found.`
> 
> I spent a day installing xcode on a MacBook just to compile this and still the same error, i thought it was version problem.

Change Signing Certificate to "Mac Developer".
<img width="398" alt="Screen Shot 2021-07-10 at 11 27 29 PM" src="https://user-images.githubusercontent.com/54797110/125183800-8b39bd00-e1d6-11eb-941b-6f7faad9c38b.png">

**Comment by NSSpiral** [comment]
> 
> 
> Wtf why there is no compiled binary? Xcode is throwing error on Big Sur and on Mojave:
> 
> `No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "E4V2A7WYY7" with a private key was found.`
> 
> I spent a day installing xcode on a MacBook just to compile this and still the same error, i thought it was version problem.

There are compiled binaries [here](https://github.com/NSSpiral/Blackb0x/releases)

You can also just choose for it not to sign at all if you're just running it locally.
