### ISSUE TITLE
Jailbreak active but no Kodi after reboot Apple TV 3 (A1469) 8.4.4 OS

### ISSUE THREAD

**Issue by doctoralvarez** [NSSpiral/Blackb0x#27]
Hi, great job on this jailbreak, Ihavedone all steps until it shows the success message on BlackB0x app (Mac). After that I disconnect microUSB cable and then disconnect and connect OR power-cycle ATV3 and then I leave to start connected to my TV Monitor on HDMI and internet ok, but after many minutes (30) it doesn’t reboot nor it loads/show any NitoTV nor Kodi icon on main screen, if I run again BB app on Mac it says Jailbreak is active, so what else can I do?? Thx in advance

**Comment by bolandross** [comment]
I'm having the same problem, any ideas?

**Comment by NSSpiral** [comment]
Can you post the output of blackb0x.log? It should be accessible in the default directory (/var/mobile/Media) with iFunbox or iMazing.

**Comment by bolandross** [comment]
I repeated the jailbreak via app and this time I received the message that it’s finished. Maybe something went wrong at the first time.
