### ISSUE TITLE
nothing has changed

### ISSUE THREAD

**Issue by ozziepadilla** [NSSpiral/Blackb0x#29]
Hi I have use your patcher to jailbreak my Apple TV 3gn but I did not see any difference , when I see in the blackb0.. jailbreak installed I have unplugged then plug in my device to my tv and everything is the same as I have before, so what is suppose to do after says Jailbreak installed?

**Comment by NSSpiral** [comment]
Power it on with the internet connected and in 5-10 minutes you should see Kodi and nitoTV. If not then post the contents of blackb0x.log from iFunbox or iMazing so I can see which step it failed on.

**Comment by adaschum** [comment]
I can't get NitoTv either, maybe I need to reset my jailbreak and bring back to original because I used the first one that was released before updated.  Not sure how to update to the new updated one when Im already jailbroke.

**Comment by NSSpiral** [comment]
A restore and jailbreak should fix your problem.

**Comment by ozziepadilla** [comment]
> Power it on with the internet connected and in 5-10 minutes you should see Kodi and nitoTV. If not then post the contents of blackb0x.log from iFunbox or iMazing so I can see which step it failed on.

Funny 😄, 5 to 10 minutes , let me tell you it’s already many hours and everything is the same on my Apple TV

**Comment by NSSpiral** [comment]
You restored and tried which build?

**Comment by ozziepadilla** [comment]
> You restored and tried which build?

One more time , I plug in my Mac my Apple TV 3gn using the micro usb cable and the power cable I follow your instructions holding DOWN button and MENU the led indicator flashing quickly then I see hold DOWN button and PLAY/PAUSE button until I see jailbreak installed then I plug it back in to my tv and nothing change in 5 to 10 minutes and from now has been hours since  I did your method but nothing change in my Apple TV , by the way the UI looks terrible because can’t read what the buttons says until y put it over a white page just to read clearly you or whoever develope did this ui need to add a best way reading

**Comment by NSSpiral** [comment]
> 
> 
> > You restored and tried which build?
> 
> One more time , I plug in my Mac my Apple TV 3gn using the micro usb cable and the power cable I follow your instructions holding DOWN button and MENU the led indicator flashing quickly then I see hold DOWN button and PLAY/PAUSE button until I see jailbreak installed then I plug it back in to my tv and nothing change in 5 to 10 minutes and from now has been hours since I did your method but nothing change in my Apple TV , by the way the UI looks terrible because can’t read what the buttons says until y put it over a white page just to read clearly you or whoever develope did this ui need to add a best way reading

Which version of blackb0x? 0.1, 0.2, 0.3, 0.4, 0.5? Try with the newest please.

**Comment by ozziepadilla** [comment]
> > > You restored and tried which build?
> > 
> > 
> > One more time , I plug in my Mac my Apple TV 3gn using the micro usb cable and the power cable I follow your instructions holding DOWN button and MENU the led indicator flashing quickly then I see hold DOWN button and PLAY/PAUSE button until I see jailbreak installed then I plug it back in to my tv and nothing change in 5 to 10 minutes and from now has been hours since I did your method but nothing change in my Apple TV , by the way the UI looks terrible because can’t read what the buttons says until y put it over a white page just to read clearly you or whoever develope did this ui need to add a best way reading
> 
> Which version of blackb0x? 0.1, 0.2, 0.3, 0.4, 0.5? Try with the newest please.

Hey look I am not a newbie to this , your 0.5 release is what I use but still looks terrible anyway thd black background makes the app not readable

**Comment by NSSpiral** [comment]
Which version of macOS?

**Comment by ozziepadilla** [comment]
> Which version of macOS?

macOS Big Sur 11.4

**Comment by NSSpiral** [comment]
Would you mind pasting the contents of blackb0x.log using iFunbox?

**Comment by ozziepadilla** [comment]
I am always up to date in all my devices and explain me what is suppose to do your jailbreaking thing?

**Comment by NSSpiral** [comment]
I need to know what step failed, giving me the blackb0x.log output would let me see that.

**Comment by ozziepadilla** [comment]
> Would you mind pasting the contents of blackb0x.log using iFunbox?

I am away from home at work right now I can’t but there is not logs of anything i double check that after

**Comment by ozziepadilla** [comment]
> I need to know what step failed, giving me the blackb0x.log output would let me see that.

Nothing fails following the instructions that all then says “Jailbreak installed “

**Comment by NSSpiral** [comment]
That is installing the jailbreak, the device configures the jailbreak on first boot. I'll need to see where it failed to do that (blackb0x.log). If that file isn't there then I'll need you to run blackb0x from terminal so I can see where the install fails.

cd blackb0x.app/Contents/MacOS
./blackb0x

**Comment by ozziepadilla** [comment]
> That is installing the jailbreak, the device configures the jailbreak on first boot. I'll need to see where it failed to do that (blackb0x.log). If that file isn't there then I'll need you to run blackb0x from terminal so I can see where the install fails.
> 
> cd blackb0x.app/Contents/MacOS
> ./blackb0x

Ok once I get home this afternoon I will do that but tell me your jailbreaking  makes what on this Apple TV ? Allows to downloads  apps ?

**Comment by NSSpiral** [comment]
Through nitoTV you'll be able to install random Apple TV tools. Non-UI iOS packages/tools also run. Most people jailbreak just to use Kodi (3rd party media player).

**Comment by ozziepadilla** [comment]
They won’t allows to download YouTube and others streaming apps like Disney + and others like HBOMAX

**Comment by NSSpiral** [comment]
Possibly youtube. Definitely not Disney+/HBOMAX, sorry.

**Comment by joshblah555** [comment]
> That won’t allows to download YouTube and others streaming apps like Disney + and others like HBOMAX

Youtube, HBOMAX and other sources are slowly being shutdown on older devices simply because they're more updated on the newer generations (Apple TV 4/4K).

If you wish to have quality entertainment then it's a wiser choice to invest in the 4th generation (HD) seeing as it has much more capabilities than the 3rd gen.

**Comment by ozziepadilla** [comment]
I have two of those also 4K but I wanted to make this 3gn get at least streaming apps but your jailbreaking only offer things that I don’t like and only YouTube is not that what I expected , suggestion change a little bit your UI the black background makes the button no readables , I am goma close this issue sorry
