### ISSUE TITLE
Stuck on "Downloading firmware components"

### ISSUE THREAD

**Issue by pedroblourenco** [NSSpiral/Blackb0x#3]
After (successfully?!?) jailbreaking my Apple TV (A1469) I tried booting the device with Blackb0x but it got stuck on "Downloading firmware components". I presume I must be doing something wrong. What could it be?
Thank you for helping!

**Comment by NSSpiral** [comment]
You don't need to boot Apple TV 3 with blackb0x, it is untethered once installed. Just plug it into your TV and let it start.

**Comment by pedroblourenco** [comment]
> You don't need to boot Apple TV 3 with blackb0x, it is untethered once installed. Just plug it into your TV and let it start.

Thank you!
Before trying to reboot it through Blackb0x I connected my Apple TV to the TV; since it was showing the restore screen I assumed it needed tethering. I will try again, performing the jailbreak procedure from scratch.

**Comment by adaschum** [comment]
Kodi appears and no nitoTV yet for me too.  I also can't connect with any sources with Kodi to addon but my other Kodis on iPhone devices can.  Almost like Kodi isn't running correctly.

**Comment by pedroblourenco** [comment]
> Kodi appears and no nitoTV yet for me too. I also can't connect with any sources with Kodi to addon but my other Kodis on iPhone devices can. Almost like Kodi isn't running correctly.

Not that I fully understand the jailbreak scene, but from what the authors of Blackb0x have said nitoTV will automatically install when the awkwardTV repo comes back online.
