### ISSUE TITLE
KVM incompatible?

### ISSUE THREAD

**Issue by nacabaro** [NSSpiral/Blackb0x#30]
Hello, I just heard from this project and I wanted to try it out in my Apple TV 3,2. Running macOS High Sierra 10.13.6 (17G14042) on a KVM based virtual machine.

The issue I'm facing is the inmediate crash of the application after entering into DFU mode, in which blackb0x will find the Apple TV, but will inmediately crash. Further debugging by using the terminal results in this:
![Screen Shot 2021-07-14 at 02 14 32](https://user-images.githubusercontent.com/42542644/125541133-d15768d4-a73e-488c-b512-68103f78c1f6.png)

By insisting a bit more, sometimes it will let me progress, but gets stuck in this step:
![Screen Shot 2021-07-14 at 02 03 36](https://user-images.githubusercontent.com/42542644/125541224-1ddbec45-9ebf-4ea3-8977-325e9498a2bd.png)

If this is an issue with the KVM itself, let me know.

Thanks in advance.

**Comment by NSSpiral** [comment]
I'm working on fixing issues on older macOS versions (including High Sierra).

**Comment by NSSpiral** [comment]
There's a new build here [here](https://github.com/NSSpiral/Blackb0x/releases/tag/0.5) if you want to try it. I'm not sure checkm8 will work through KVM though.

**Comment by nacabaro** [comment]
UPDATE: Apparently the tight latency issues in KVM will not work for using Blackb0x, tried in my Late 2009 iMac with El Capitán and it worked after a few attempts.
