### ISSUE TITLE
Video Instruction?

### ISSUE THREAD

**Issue by haxcop** [NSSpiral/Blackb0x#31]
Could it be possible to have a short video showing the step by step procedure to use your code?
Thanks!

**Comment by joshblah555** [comment]
> Could it be possible to have a short video showing the step by step procedure to use your code?
> Thanks!

To.. compile it? or to use the app?

**Comment by fratinize** [comment]
Where do I find the .app?

**Comment by fratinize** [comment]
Found it on this link ty
Download the "Blackb0x.app.zip" from the assets list here: https://github.com/NSSpiral/Blackb0x/releases

**Comment by haxcop** [comment]
> > Could it be possible to have a short video showing the step by step procedure to use your code?
> > Thanks!
> 
> To.. compile it? or to use the app?

To install the app, so I imagine using the app because It looks like I ended doing it correctly but Kodi never show up
