### ISSUE TITLE
How to restore Apple TV A1469 to factory state (without jailbreak)

### ISSUE THREAD

**Issue by alexthe1st-dev** [NSSpiral/Blackb0x#34]
Jailbroken my ATV 3 (1469) 8.4.4 with the release 0.2 - without NitoTV.
Tried to restore through iTunes - but kodi is on the same place after restore.
Tried to rejailbreak with newer version - nothing happens.
Please help to restore to factory settings and will try newer release to rejailbreak.
Thank you in advance

**Comment by NSSpiral** [comment]
Put it in DFU mode then restore in Finder or iTunes depending on macOS version.

**Comment by joshblah555** [comment]
Alternatively; if iTunes/Finder fails to work, you may also use `idevicerestore`.
