### ISSUE TITLE
What am I missing here

### ISSUE THREAD

**Issue by applekid1029** [NSSpiral/Blackb0x#36]
I saw the reports that ATV3 could be jailbroken with Blackb0x so here I am - I download the blackb0x.app.zip file, unpack it. I read the instructions for the 3rd time and even visit youtube for a tutorial since I cannot even get the application open. There is no "Jailbreak" application included, even a complete dipshit did a video on this Blackb0x jailbreaking a ATV yet doesnt even have one (smh) and claims oh its so easy....yeah if the application worked I'm sure it is. 

Whos got the magic wand?

**Comment by NSSpiral** [comment]
> I saw the reports that ATV3 could be jailbroken with Blackb0x so here I am - I download the blackb0x.app.zip file, unpack it. I read the instructions for the 3rd time and even visit youtube for a tutorial since I cannot even get the application open. There is no "Jailbreak" application included, even a complete dipshit did a video on this Blackb0x jailbreaking a ATV yet doesnt even have one (smh) and claims oh its so easy....yeah if the application worked I'm sure it is.
> 
> Whos got the magic wand?

What's the issue with opening it? Did you right click blackb0x.app and click Open? Does it crash on open?
