### ISSUE TITLE
blackbox jailbreak

### ISSUE THREAD

**Issue by appleboy49** [NSSpiral/Blackb0x#37]
Hi<img width="948" alt="Screenshot 2021-07-16 at 13 17 14" src="https://user-images.githubusercontent.com/87529537/125946366-551cf616-5681-4044-8c28-14270c5a6500.png">all
Not sure where I am going wrong have been trying this all morning now with no joy.
I am running on my Mac big sur 11.4
My apple is Apple TV 3 running 8.4.4
I have ran  the software on the Mac connected the Apple TV.
Clicked on the jailbreak option.
When I have used the down and menu button then the menu and play button until it flashes
Clicked on j
<img width="948" alt="Screenshot 2021-07-16 at 13 17 14" src="https://user-images.githubusercontent.com/87529537/125946322-13331b5d-b37f-4a0b-8446-84e44061332e.png">
ailbreak and I get the message o say its completed.Unplugged it and plugged into the tv and left for an hour and Kodi has not installed.
Also I have left it plugged into the laptop for an hour and I get no other messages on black box.
Please can someone point me in the right direction.

**Comment by joshblah555** [comment]
You can try rejailbreaking without unplugging the power, then waiting a few minutes to see if the apps show up..

**Comment by NSSpiral** [comment]
> Hi<img alt="Screenshot 2021-07-16 at 13 17 14" width="948" src="https://user-images.githubusercontent.com/87529537/125946366-551cf616-5681-4044-8c28-14270c5a6500.png">all
> Not sure where I am going wrong have been trying this all morning now with no joy.
> I am running on my Mac big sur 11.4
> My apple is Apple TV 3 running 8.4.4
> I have ran the software on the Mac connected the Apple TV.
> Clicked on the jailbreak option.
> When I have used the down and menu button then the menu and play button until it flashes
> Clicked on j
> <img alt="Screenshot 2021-07-16 at 13 17 14" width="948" src="https://user-images.githubusercontent.com/87529537/125946322-13331b5d-b37f-4a0b-8446-84e44061332e.png">
> ailbreak and I get the message o say its completed.Unplugged it and plugged into the tv and left for an hour and Kodi has not installed.
> Also I have left it plugged into the laptop for an hour and I get no other messages on black box.
> Please can someone point me in the right direction.

Were you able to resolve this?

**Comment by songdifan** [comment]
(3,1 Only) PWN with Arduino + synackuk's fork of checkm8-A5

**Comment by appleboy49** [comment]
Hi there I have left the Apple TV on and when I try to jail break it just sits flashing and the tv is blank have left it for over an hour.
If I unplug and restart it comes on with no apps installed

**Comment by NSSpiral** [comment]
> Hi there I have left the Apple TV on and when I try to jail break it just sits flashing and the tv is blank have left it for over an hour.
> If I unplug and restart it comes on with no apps installed

Which model Apple TV, which macOS version, etc. Paste blackb0x.log using iFunbox if you can.

**Comment by appleboy49** [comment]
I am using big sur 11.7
The Apple TV model number is a1427
Not sure how to get the logs out of the software for you

**Comment by NSSpiral** [comment]
Double click blackb0x.log and paste the contents here (or attach it).

**Comment by appleboy49** [comment]
Hi There sorry to sound thick but where do I get the blackb0x.log app from as I have only got blackb0x installed

**Comment by songdifan** [comment]
A1427, need to do checkm8-A5 first。

**Comment by appleboy49** [comment]
How do I do that mate sorry this is the first time that I have tried to jail break this so I am a complete novice

**Comment by joshblah555** [comment]
> How do I do that mate sorry this is the first time that I have tried to jail break this so I am a complete novice

`PWN with Arduino + synackuk's fork of checkm8-A5`

**Comment by appleboy49** [comment]
Can anyone help me with this 
If yiu can give me a step by step guide as I keep saying I have never done this before and still struggling to jailbreak the Apple TV

**Comment by WhiteO** [comment]
Hello everyone,
I used blackbox yesterday, completed all the points, but after restarting atv3, not my TV and not my DHCP server does not see atv3, how can I make a reinstall jb?
i have atv3 1469 with ios 7.6.2

**Comment by appleboy49** [comment]
How cam this be closed I still have not solved the problem 
As I am new to this please can someone give me an idiot's guide to jailbreakjng this box I have tried with my apple tv HD on this 14 and my old apple tv 2

**Comment by NSSpiral** [comment]
The newest build should solve your problem, kodi will appear after you reinstall and rejailbreak

**Comment by appleboy49** [comment]
Can you send me a link to the latest file please

**Comment by NSSpiral** [comment]
https://github.com/NSSpiral/Blackb0x/releases
