### ISSUE TITLE
Avast blocks the app

### ISSUE THREAD

**Issue by vgf62** [NSSpiral/Blackb0x#40]
Avast blocks the app due MacOS:Agent-QN [PUP] infection. 

<img width="626" alt="Schermata 2021-07-17 alle 17 39 00" src="https://user-images.githubusercontent.com/1553462/126042196-866b50ca-35ab-4cad-a1a8-b3aacb537cc8.png">

Is this one a false-positive?

**Comment by NSSpiral** [comment]
> Avast blocks the app due MacOS:Agent-QN [PUP] infection.
> 
> <img alt="Schermata 2021-07-17 alle 17 39 00" width="626" src="https://user-images.githubusercontent.com/1553462/126042196-866b50ca-35ab-4cad-a1a8-b3aacb537cc8.png">
> 
> Is this one a false-positive?

As long as you downloaded blackb0x from the releases page on this GitHub repo it is a false positive.
