### ISSUE TITLE
A1427 and tvOS8.4.4

### ISSUE THREAD

**Issue by CDX-24** [NSSpiral/Blackb0x#45]
Hi there,
So I have an Apple TV 3rd gen (A1427) running on tvOS 8.4.4 (somehow, the version displayed on the Apple tv interface shows 7.7, maybe due to the change to the tvOS name).

I have used an arduino UNO with the USB host shield and I get a positive result according to the serial output of the arduino.
But I don’t have any success with the Blackb0x tool, it often states « jailbreak active » altough I don’t see Kodi anywhere.
I had a few success where I see the software being downloaded and installed on Blackb0x after unplugging the cable directly after using the arduino but when I reboot the Apple TV, nothing.

i would be glad if you could tell me what I am doing wrong, or if my device is incompatible.
My goal is to have an untethered jailbreak. 

Thank you !
Chris.

**Comment by Djugly** [comment]
Bro, same thing happened to me until I had the apple tv 3 connected to internet 20 minutes.

**Comment by CDX-24** [comment]
You were right !!! Left it on for quite some time and nito and Kodi appeared ! I did not understand though that it is an app and not directly a « system » on which the Apple TV boots ! Next time I will learn to wait 😂
