### ISSUE TITLE
ATV 3 (A1469) refuses to enter DFU mode

### ISSUE THREAD

**Issue by ads105** [NSSpiral/Blackb0x#47]
Hello,
I've been trying to use Blackb0x to jailbreak my Apple TV 3 (A1469), which is running 8.4.4, but it won't even get as far as entering DFU mode. I've tried holding down + menu for 6 seconds, 7 seconds, 1 minute, 3 minutes...no joy. I just get a spinning icon, the option to cancel, and the instructions for how to enter DFU mode on the screen (which is quite annoying by this point).

Can anyone shed any light on it?

I'm on a 2012 MacBook, running Catalina 10.15.7

Thanks!

**Comment by NSSpiral** [comment]
Make sure you have a genuine ATV remote (thin silver one). Make sure the battery has enough charge to continuously hold the buttons down. You can also try completely removing the Apple TV from power and restarting the app.

**Comment by micho2005** [comment]
> Hello,
> I've been trying to use Blackb0x to jailbreak my Apple TV 3 (A1469), which is running 8.4.4, but it won't even get as far as entering DFU mode. I've tried holding down + menu for 6 seconds, 7 seconds, 1 minute, 3 minutes...no joy. I just get a spinning icon, the option to cancel, and the instructions for how to enter DFU mode on the screen (which is quite annoying by this point).
> 
> Can anyone shed any light on it?

i have same issue and i’m using the original remote any help

**Comment by micho2005** [comment]
i have same issue and i’m using the original remote any help?

**Comment by ads105** [comment]
Thanks - I tracked down a genuine remote and it worked.
