### ISSUE TITLE
How to unjailbreak

### ISSUE THREAD

**Issue by Aappletv** [NSSpiral/Blackb0x#48]
I would like to know how to unjailbreak my Apple TV 3 gen

**Comment by NSSpiral** [comment]
Restore to fully unjailbreak, or remove the symlink at /usr/libexec/rtbuddyd to prevent the untether from jailbreaking on boot.

**Comment by Aappletv** [comment]
Canot restore. The Apple TV is not able to download software because of the OTA blocker

**Comment by NSSpiral** [comment]
> Canot restore. The Apple TV is not able to download software because of the OTA blocker 

Put Apple TV into DFU mode, restore in either Finder or iTunes depending on macOS version.

**Comment by ottawagamerz** [comment]
one go here https://ipsw.me/ pick the apple product you have than it will have a check mark what u can download than after u download the firmware plug in apple tv box to pc and hold shift and hit restore and choose the one u downloaded if it works just wait if it doesn't try another from that page very simple
