### ISSUE TITLE
Apple TV not restarting 

### ISSUE THREAD

**Issue by lolilol123456789** [NSSpiral/Blackb0x#49]
Why doesn’t my Apple TV restart after the jailbreak is done? It says that I need to connect my Apple TV to iTunes. I have an 3.2 with version 8.4.6

**Comment by lolilol123456789** [comment]
![image](https://user-images.githubusercontent.com/39464124/127527317-bc3c0a80-85ca-4cb6-a5ae-58db9ad64e34.jpeg)

**Comment by AmakoYoko** [comment]
hi, did you succeed? I try several solutions but nothing for the moment...

**Comment by lolilol123456789** [comment]
Nope, but I actually found this Apple TV so it's not really a problem 4me. But it would be awesome to get the web working

**Comment by Martijnsvb** [comment]
I have the same Apple TV and mine also did this. What I did was holding the down + menu buttons untill the light starts flickering and then let go of the buttons. This made my device restart. Hope this also works for you guys!

**Comment by AmakoYoko** [comment]
> I have the same Apple TV and mine also did this. What I did was holding the down + menu buttons untill the light starts flickering and then let go of the buttons. This made my device restart. Hope this also works for you guys!

And after that you got Kodi?

**Comment by Martijnsvb** [comment]
> And after that you got Kodi?

Yes. Keep in mind that you have to wait a couple of minutes after it restarts for Kodi to show up (Step 5 in the guide).

**Comment by lolilol123456789** [comment]
Did that work for anyone now?

**Comment by lolilol123456789** [comment]
![image](https://user-images.githubusercontent.com/39464124/127638583-4f677a18-93b7-4234-92ee-ab8ce62a0fef.jpeg)

What do I do now?

**Comment by AmakoYoko** [comment]
I still have nothing, I waited almost an hour and still no kodi ...

I think it's because you are not connected to the internet lolilol123456789

**Comment by lolilol123456789** [comment]
Okay I see

**Comment by lolilol123456789** [comment]
Has anyone got the Apple TV jailbreak working? If so could you make a written tutorial of how you got it working?

**Comment by Martijnsvb** [comment]
> Has anyone got the Apple TV jailbreak working? If so could you make a written tutorial of how you got it working?

It's working for me and I just followed the steps in the readme (copy pasted here):

IMPORTANT: Make sure your device is connected to the internet for the first boot.

Steps to Jailbreak:
1. Plug in your Apple TV via micro-USB AND plug in the power cable.
2. Open Blackb0x - Right click Blackb0x.app then click Open (Important)
3. Click Jailbreak.
4. Follow instructions to enter DFU mode
5. Once Jailbreak has finished installing connect to your tv and wait 5-10 minutes until Kodi appears (Be patient, go have a coffee).

If the Apple TV shows the first screen you sent hold down + menu until the light on the device starts flickering and it should restart. After that wait for step 5 to finish.

This worked for me. It's running for about 2 weeks now without any issues.

**Comment by AmakoYoko** [comment]
I did absolutely everything that is said in the Readme + restart with the remote control but it will be almost 3 hours that I expect and still no kodi ...

**Comment by mammamorta** [comment]
apple tv a1469 (7.7) doesn't restart after jailbreak. with soft restart down+menu, restart back to main menu. trying to connect again by usb cable app doesn't recognize the apple tv anymore. So, process abandoned. peace

**Comment by mammamorta** [comment]
> I did absolutely everything that is said in the Readme + restart with the remote control but it will be almost 3 hours that I expect and still no kodi ...

5-10 minutes its just depending on your internet speed connection, with 500 Mbit/s it should take no more than 1 minute to roll out. After that time, its mean that jailbreak probably doesn't work.

**Comment by Vipizz** [comment]
Seems to be something wrong with one or more repositorys. For me with atv3,1 , arduino+checkm8 and jailbreak on mac work as It should. But when atv boot with internet and should post install apps I got errors in blackb0x log and it never reboots by itself. I see that it tries to install the apps in log every time it boots. But then nothing happends.

**Comment by classek** [comment]
Make sure that Jailbreak worked with ssh to AppleTv. ssh@root.AppletvIp password alpine. Mine worked (Apple TV 3.1) but Kodi isn’t installed.

**Comment by Devnol** [comment]
Same, I did Down+Menu when it showed connect to iTunes, I can SSH to it but no Kodi, do I do the jailbreak again or what?

**Comment by Martijnsvb** [comment]
> Same, I did Down+Menu when it showed connect to iTunes, I can SSH to it but no Kodi, do I do the jailbreak again or what?

As mentioned in #51 the repo that is supposed to provide Kodi and NitoTV is currently down so they will not get installed automatically. I see the issue contains a workaround that some people have success with so you could try that.

Good luck!

**Comment by Devnol** [comment]
I tried that workaround and it did sort of work but as mentioned kodi is on a really old version and has no wifi access and thus no addons.

**Comment by NSSpiral** [comment]
If the Apple TV reboots with the usb still connected it will go back into recovery mode. Need to unplug the power and usb before plugging it into the TV.
