### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by m0sx123** [NSSpiral/Blackb0x#5]
Make compatible with Mac OS mojave. Thanks

**Comment by NSSpiral** [comment]
Within the next couple of days

**Comment by NSSpiral** [comment]
New build (0.4) should run on Mojave. Let me know if it works so I can close this issue.

**Comment by m0sx123** [comment]
New build run without problems and finding Apple tv, but button on my remote is broken and i can't go in dfu mode to test jailbreak... :( thanksss for everything

**Comment by ghoulsngoblins** [comment]
Still doesn’t work for me

**Comment by NSSpiral** [comment]
> Still doesn’t work for me

What's the issue you're having?

**Comment by ghoulsngoblins** [comment]
It can’t open because apple can’t check for malicious software

**Comment by NSSpiral** [comment]
> 
> 
> It can’t open because apple can’t check for malicious software

Right click blackb0x.app, click Open instead of double clicking it.
