### ISSUE TITLE
Can not wget 

### ISSUE THREAD

**Issue by faboy1053** [NSSpiral/Blackb0x#62]
Hi guys. I know the joshtv have been down for sometimes but i can not make my apple tv to be jailbroken. 
i'm stuck at step 2 for manually jailbreak. when type this wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add - 

Then its appeared: 
OpenSSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
Unable to establish SSL connection.
gpg: no valid OpenPGP data found.

Can someone help me out cause i really need its to be jailbroken :(

**Comment by NSSpiral** [comment]
Newest build should install Kodi automatically again
