### ISSUE TITLE
Install Kodi on AppleTV 3,2 (A1469)

### ISSUE THREAD

**Issue by TrickShotMLG02** [NSSpiral/Blackb0x#64]
I have used BlackB0X to jailbreak my appletv 3,2 (A1469) running OS 8.4.3.
Everything worked, I can establish a ssh connection to the atv, but Kodi wasn't installed.

How can I manually install it via ssh?

**Comment by turtlenation85** [comment]
hey man have you figured it out yet??

**Comment by TrickShotMLG02** [comment]
No, still not

**Comment by GISGuy** [comment]
I do able to manually install kodi successfully via ssh. but the kodi icon doesn't show up at all, even after reboot.
FYI, https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Apple_TV_4_and_5_(HD_and_4K)
I used version 18.0-iphoneos btw.

**Comment by TrickShotMLG02** [comment]
Same here, but i used kodi 16.4

**Comment by 22cms** [comment]
iOS and Apple TV 2/3 builds wre different, even woth the same Kodi Version. Try opening the deb files of both 14.2 atv2 and 14.2 iphoneos-arm and you'll see s ton of different files between each other. Kodi likely needs to be recompiled to run on ATV 3, but I don't really know how (couldn't find any information about compiling Kodi 14.2 for apple tv 2, so finding out how to compile a newer version is basically impossible) and there's guarantee that it'd run smoothly enough on such hardware

**Comment by NSSpiral** [comment]
Newest build should install Kodi automatically again

**Comment by nixcamic** [comment]
Just in case it doesn't (mine didn't) ssh in with root:alpine, then run 

apt-get update
apt-get upgrade

(may have to run:
apt-get install -f
apt-get upgrade
again if it fails first time)

then: 

apt-get install org.xbmc.kodi-atv2
