### ISSUE TITLE
A1427 kodi or nitotv not installing

### ISSUE THREAD

**Issue by turtlenation85** [NSSpiral/Blackb0x#65]
this is what happens when I try to manual install kodi and nitotv 
wget -O- http://apt.awkwardtv.org/awkwardtv.pub | apt-key add -
--2021-11-12 13:40:34--  http://apt.awkwardtv.org/awkwardtv.pub
Resolving apt.awkwardtv.org... 155.138.254.229
Connecting to apt.awkwardtv.org|155.138.254.229|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://apt.awkwardtv.org/awkwardtv.pub [following]
--2021-11-12 13:40:34--  https://apt.awkwardtv.org/awkwardtv.pub
Connecting to apt.awkwardtv.org|155.138.254.229|:443... connected.
OpenSSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
Unable to establish SSL connection.
gpg: no valid OpenPGP data found.

**Comment by NSSpiral** [comment]
Newest build should install Kodi automatically again
