### ISSUE TITLE
No kodi or NitoTV

### ISSUE THREAD

**Issue by FedetheTV** [NSSpiral/Blackb0x#66]
So I bought a used Mac to perform this jailbreak. The Jaibreak completed successfully, so I waited an hour and there's no Kodi nor NitoTV in my menu. How do I fix this?

**Comment by phvlkn** [comment]
same problem

**Comment by melkosofter** [comment]
forget, this app is abandoned, nothing will install, josh.tv repo is down

**Comment by NSSpiral** [comment]
Newest build should install Kodi automatically again
