### ISSUE TITLE
appletv3 jailbreak success but use dpkg install Kodi -14.2 fail

### ISSUE THREAD

**Issue by maokk** [NSSpiral/Blackb0x#69]
Hi ,
    thanks for you great work, I have jailbreak my appleTV3 success, but after I download kid-14.2 from XBMC and want use dpkg -I install it , I got error below, hope somebody give me some suggestions, thanks

Apple-TV-music:~/Media root# dpkg -i org.xbmc.kodi-atv2_14.2-0_iphoneos-arm.deb Selecting previously unselected package org.xbmc.kodi-atv2.
(Reading database ... 1474 files and directories currently installed.)
Preparing to unpack org.xbmc.kodi-atv2_14.2-0_iphoneos-arm.deb ...
Unpacking org.xbmc.kodi-atv2 (14.2-0) ...
dpkg: dependency problems prevent configuration of org.xbmc.kodi-atv2:
 org.xbmc.kodi-atv2 depends on org.awkwardtv.whitelist; however:
  Package org.awkwardtv.whitelist is not installed.
 org.xbmc.kodi-atv2 depends on com.nito.updatebegone; however:
  Package com.nito.updatebegone is not installed.

dpkg: error processing package org.xbmc.kodi-atv2 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 org.xbmc.kodi-atv2

**Comment by btadine** [comment]
Look at the other issues, they have the same problem as you. The repo for those packages is down and there haven't been advances in providing new repos. Manual install is the only option

**Comment by NSSpiral** [comment]
Newest build should install Kodi automatically again
