### ISSUE TITLE
Not run

### ISSUE THREAD

**Issue by Blunocia** [NSSpiral/Blackb0x#7]
it gives me error on the second string 

#include <openssl/aes.h> 

tells me "file not found"

**Comment by starnaultmathis** [comment]
Same problem for me...

**Comment by activea** [comment]
worked after checking this post.. https://stackoverflow.com/questions/45693149/openssl-aes-h-file-not-found-on-mac

First check if the path pointed out by $(brew --prefix openssl)/include exists.

If above is fine, you can try

$ cd /usr/local/include
$ ln -s ../opt/openssl/include/openssl .
