### ISSUE TITLE
Can't open latest version of blackb0x

### ISSUE THREAD

**Issue by TrickShotMLG02** [NSSpiral/Blackb0x#70]
I have downloaded the latest version of blackb0x and tried to open it. But it gives me the following error:

![Bildschirmfoto 2021-12-20 um 12 14 45](https://user-images.githubusercontent.com/43967908/146758939-89a68957-3fbc-443c-ad90-759194c29b30.png)

Do you have any solutions?

**Comment by petitgris** [comment]
Same problem here ...

**Comment by NSSpiral** [comment]
Fixing shortly!

**Comment by NSSpiral** [comment]
Replaced version 0.6 with a new one

**Comment by TrickShotMLG02** [comment]
Now i can open the app, but there is no GUI appearing. And the top menu also doesn't work at all

**Comment by NSSpiral** [comment]
Ok version 0.6 should work on everything from 10.11+

**Comment by TrickShotMLG02** [comment]
I was able to install the jailbreak and i can confirm that it is working. But i dont habe kodi on the atv

**Comment by TrickShotMLG02** [comment]
fixed it by following these steps:

https://github.com/NSSpiral/Blackb0x/issues/51#issuecomment-904908206
