### ISSUE TITLE
No apps icons

### ISSUE THREAD

**Issue by ElliotDark** [NSSpiral/Blackb0x#72]
I was sucsesseful jailbroken my apple tv(**A1469**)
After install it no auto reboot, stuck on recovery( i wait ~30 min, then reboot apple TV manually)
No have any additional icons after reboot and waitng
I was try install Kodi and other apps from cli with `apt-get`(latest kodi from repo) and locally with `dpkg`(Kodi 14,2), no results
All applications have folders in `/Applications`
`uicache` command dont help with this issue
On request can provide any logs from appleTV

**Comment by NSSpiral** [comment]
Can you please paste the log from /var/mobile/Media/blackb0x.log?

**Comment by ElliotDark** [comment]
[blackb0x.log](https://github.com/NSSpiral/Blackb0x/files/7767771/blackb0x.log)
[blackb0x_install.log](https://github.com/NSSpiral/Blackb0x/files/7767772/blackb0x_install.log)

**Comment by NSSpiral** [comment]
apt-get -y --force-yes install org.xbmc.kodi-atv2

What is the output from this?
And does anything appear after killall -9 backboardd?

**Comment by ElliotDark** [comment]
Kodi icon now in menu list after `apt-get -y --force-yes install org.xbmc.kodi-atv2` 
you are breathtaking =)
thank you!
