### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by HoSpeLL** [NSSpiral/Blackb0x#9]
Hello everyone. 
How are we supposed to run the program on MacOS in order to jailbreak AppleTV?

**Comment by NSSpiral** [comment]
Right click Blackb0x.app, click Open then follow the instructions.

**Comment by HoSpeLL** [comment]
Hmmmm. I can’t find .app

**Comment by pedroblourenco** [comment]
> Hmmmm. I can’t find .app

Download the "Blackb0x.app.zip" from the assets list here: https://github.com/NSSpiral/Blackb0x/releases
