### ISSUE TITLE
A1469 Stuck on the recovery mode

### ISSUE THREAD

**Issue by christineynt** [NSSpiral/Blackb0x#93]
model: A1469 Apple tv3
computer: MacBook Pro 2017
I am not sure how to do the step 0 so I have skipped it first and see if it works. So I have started the steps from step 1.
When I tried to enter the DFU mode, the screen ask me to press down + menu and then press menu + play/pause button. After that, the screen ask me to press down + menu again. However, the light kept flashing rapidly but the screen still asking me to press  down + menu button. At this time I was thinking I fail to jailbreak so I go to finder and press Apple TV and try to restore. After loading a message told me to disconnect the computer and connect to tv. When I connect to tv, it ask me to restore. And I connect to computer again and restore and connect to tv and the screen still ask me to restore. So I have stuck in the recovery mode. What should I do now and How can I enter DFU mode is it because I didn't do the step 0?

**Comment by NSSpiral** [comment]
You don't need arduino for A1469. Once the recovery mode screen appears
then you can just unplug it and connect it to your TV.
